# Generated by Django 3.2.6 on 2021-08-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weight_class', models.CharField(choices=[('Heavy vehicle', 'Heavy vehicle'), ('Light vehicle', 'Light vehicle')], max_length=30)),
                ('vehicle_brand', models.CharField(choices=[('Toyota', 'Toyota'), ('Audi', 'Audi'), ('Nissan', 'Nissan'), ('Mercedes', 'Mercedes'), ('Vox Wagon', 'Vox Wagon'), ('BMW', 'BMW'), ('Range Rover', 'Range Rover')], max_length=30)),
            ],
        ),
    ]
