# Generated by Django 3.2.6 on 2021-08-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=5000)),
            ],
        ),
    ]
