# Generated by Django 3.2.6 on 2021-08-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_finance'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle_Category',
            new_name='Transport',
        ),
    ]
